const questionBank = {
  tally: [
    {question: "Which shortcut key is used to create a new company in Tally ERP 9?", options: ["Alt+F1", "Alt+F2", "Alt+F3", "Alt+F4"], answer: "Alt+F3"},
    {question: "To change the current date in Tally ERP 9, which key is pressed?", options: ["F1", "F2", "F3", "F4"], answer: "F2"},
    {question: "Which function key is used to open the company features screen?", options: ["F11", "F12", "F13", "F14"], answer: "F11"},
    {question: "To create a new ledger account in Tally ERP 9, which key is used?", options: ["Alt+C", "Ctrl+L", "Alt+A", "Ctrl+N"], answer: "Alt+C"},
    {question: "Which key is used to accept a voucher in Tally ERP 9?", options: ["Ctrl+A", "Ctrl+S", "Enter", "Alt+A"], answer: "Enter"},
    {question: "To delete a voucher in Tally ERP 9, which key is used?", options: ["Alt+D", "Ctrl+D", "Alt+X", "Ctrl+X"], answer: "Alt+D"},
    {question: "Which key is used to print a report in Tally ERP 9?", options: ["Alt+P", "Ctrl+P", "F10", "F12"], answer: "Alt+P"},
    {question: "To export a report in Tally ERP 9, which key is pressed?", options: ["Alt+E", "Ctrl+E", "F11", "F12"], answer: "Alt+E"},
    {question: "Which key is used to view the daybook in Tally ERP 9?", options: ["Alt+D", "Ctrl+D", "F4", "F5"], answer: "F4"},
    {question: "To quit from Tally ERP 9, which key is used?", options: ["Alt+F4", "Ctrl+Q", "Ctrl+W", "Alt+Q"], answer: "Alt+F4"},
    {question: "Which voucher type is used for recording sales transactions?", options: ["Sales Voucher", "Purchase Voucher", "Receipt Voucher", "Payment Voucher"], answer: "Sales Voucher"},
    {question: "To record a payment made by cash, which voucher type is used?", options: ["Payment Voucher", "Receipt Voucher", "Contra Voucher", "Journal Voucher"], answer: "Payment Voucher"},
    {question: "Which voucher type is used for recording journal entries?", options: ["Journal Voucher", "Sales Voucher", "Purchase Voucher", "Receipt Voucher"], answer: "Journal Voucher"},
    {question: "To record a receipt of cash, which voucher type is used?", options: ["Receipt Voucher", "Payment Voucher", "Contra Voucher", "Journal Voucher"], answer: "Receipt Voucher"},
    {question: "Which voucher type is used for recording contra transactions?", options: ["Contra Voucher", "Receipt Voucher", "Payment Voucher", "Journal Voucher"], answer: "Contra Voucher"},
    {question: "To record a purchase of goods on credit, which voucher type is used?", options: ["Purchase Voucher", "Sales Voucher", "Receipt Voucher", "Payment Voucher"], answer: "Purchase Voucher"},
    {question: "Which voucher type is used for recording sales returns?", options: ["Sales Return Voucher", "Purchase Return Voucher", "Receipt Voucher", "Payment Voucher"], answer: "Sales Return Voucher"},
    {question: "To record a purchase return, which voucher type is used?", options: ["Purchase Return Voucher", "Sales Return Voucher", "Receipt Voucher", "Payment Voucher"], answer: "Purchase Return Voucher"},
    {question: "Which voucher type is used for recording debit notes?", options: ["Debit Note Voucher", "Credit Note Voucher", "Receipt Voucher", "Payment Voucher"], answer: "Debit Note Voucher"},
    {question: "To record a credit note, which voucher type is used?", options: ["Credit Note Voucher", "Debit Note Voucher", "Receipt Voucher", "Payment Voucher"], answer: "Credit Note Voucher"},
    {question: "Which feature in Tally ERP 9 allows you to enable GST?", options: ["F11: Features", "F12: Configuration", "F13: Statutory & Taxation", "F14: Security Control"], answer: "F11: Features"},
    {question: "To enable inventory management in Tally ERP 9, which feature is activated?", options: ["F11: Features", "F12: Configuration", "F13: Statutory & Taxation", "F14: Security Control"], answer: "F11: Features"},
    {question: "Which key is used to select a company in Tally ERP 9?", options: ["Alt+F1", "Alt+F2", "Alt+F3", "Alt+F4"], answer: "Alt+F3"},
    {question: "To alter company details in Tally ERP 9, which option is used?", options: ["Alter", "Create", "Delete", "View"], answer: "Alter"},
    {question: "Which option is used to shut a company in Tally ERP 9?", options: ["Shut Company", "Close Company", "Exit Company", "Logout"], answer: "Shut Company"},
    {question: "To restore a company in Tally ERP 9, which option is used?", options: ["Restore", "Recover", "Backup", "Restore from Backup"], answer: "Restore"},
    {question: "Which option is used to delete a company in Tally ERP 9?", options: ["Delete Company", "Remove Company", "Erase Company", "Clear Company"], answer: "Delete Company"},
    {question: "To change the financial year in Tally ERP 9, which option is used?", options: ["Change Period", "Alter Year", "Set Year", "Modify Year"], answer: "Change Period"},
    {question: "Which option is used to change the base currency in Tally ERP 9?", options: ["Alter Currency", "Set Currency", "Modify Currency", "Change Currency"], answer: "Alter Currency"},
    {question: "To enable multi-currency in Tally ERP 9, which feature is activated?", options: ["Multi-Currency", "Currency Management", "Foreign Exchange", "Currency Control"], answer: "Multi-Currency"},
    {question: "Which report displays the day-to-day transactions in Tally ERP 9?", options: ["Day Book", "Ledger", "Trial Balance", "Profit & Loss Account"], answer: "Day Book"},
    {question: "To view the trial balance in Tally ERP 9, which option is used?", options: ["Trial Balance", "Balance Sheet", "Profit & Loss Account", "Cash Flow"], answer: "Trial Balance"},
    {question: "Which report shows the profit or loss for a specific period in Tally ERP 9?", options: ["Profit & Loss Account", "Balance Sheet", "Trial Balance", "Cash Flow"], answer: "Profit & Loss Account"},
    {question: "To view the balance sheet in Tally ERP 9, which option is used?", options: ["Balance Sheet", "Profit & Loss Account", "Trial Balance", "Cash Flow"], answer: "Balance Sheet"},
    {question: "Which report shows the cash and bank balances in Tally ERP 9?", options: ["Cash/Bank Book", "Day Book", "Ledger", "Trial Balance"], answer: "Cash/Bank Book"},
    {question: "To view the stock summary in Tally ERP 9, which option is used?", options: ["Stock Summary", "Inventory Book", "Day Book", "Ledger"], answer: "Stock Summary"},
    {question: "Which report shows the outstanding receivables in Tally ERP 9?", options: ["Receivables", "Debtors", "Creditors", "Trial Balance"], answer: "Receivables"},
    {question: "To view the outstanding payables in Tally ERP 9, which option is used?", options: ["Payables", "Creditors", "Debtors", "Trial Balance"], answer: "Payables"},
    {question: "Which report shows the sales and purchase registers in Tally ERP 9?", options: ["Sales Register", "Purchase Register", "Day Book", "Ledger"], answer: "Sales Register"},
    {question: "To view the GST reports in Tally ERP 9, which option is used?", options: ["GST Reports", "Taxation Reports", "Statutory Reports", "Compliance Reports"], answer: "GST Reports"},
    {question: "To create a stock item in Tally ERP 9, which option is used?", options: ["Stock Item", "Inventory Item", "Product", "Goods"], answer: "Stock Item"},
    {question: "Which option is used to alter a stock item in Tally ERP 9?", options: ["Alter Stock Item", "Modify Stock Item", "Edit Stock Item", "Change Stock Item"], answer: "Alter Stock Item"},
    {question: "To delete a stock item in Tally ERP 9, which option is used?", options: ["Delete Stock Item", "Remove Stock Item", "Erase Stock Item", "Clear Stock Item"], answer: "Delete Stock Item"},
    {question: "Which option is used to create a godown in Tally ERP 9?", options: ["Godown", "Warehouse", "Store", "Depot"], answer: "Godown"},
    {question: "To view stock details for a particular item, which option is used?", options: ["Stock Summary", "Inventory Report", "Stock Register", "Item Ledger"], answer: "Stock Summary"},
    {question: "Which option is used to create a unit of measurement in Tally ERP 9?", options: ["Unit Creation", "Unit Setup", "Measurement", "UOM"], answer: "Unit Creation"},
    {question: "To enable GST for a company, which menu is used?", options: ["F11: Features", "F12: Configuration", "F3: Company Info", "F4: Day Book"], answer: "F11: Features"},
    {question: "Which key is used to navigate between fields in Tally ERP 9?", options: ["Enter", "Tab", "Ctrl+Tab", "Shift+Tab"], answer: "Enter"},
    {question: "Which option is used to back up company data in Tally ERP 9?", options: ["Backup", "Restore", "Save", "Export"], answer: "Backup"},
    {question: "Which key combination is used to toggle calculator in Tally ERP 9?", options: ["Alt+C", "Ctrl+C", "Alt+X", "Ctrl+X"], answer: "Alt+C"},
    {question: "Which key combination is used to create ledger while in voucher?", options: ["Alt+C", "Ctrl+L", "Alt+L", "Ctrl+C"], answer: "Alt+C"},
    {question: "Which key is used to open the ledger report for an account?", options: ["Alt+G", "Ctrl+G", "F2", "F4"], answer: "Alt+G"},
    {question: "Which key is used to print a voucher immediately?", options: ["Alt+P", "Ctrl+P", "F10", "F12"], answer: "Alt+P"},
    {question: "Which key combination is used to delete a ledger account?", options: ["Alt+D", "Ctrl+D", "Del", "Shift+D"], answer: "Alt+D"},
    {question: "To record a contra entry between cash and bank, which voucher is used?", options: ["Contra Voucher", "Payment Voucher", "Receipt Voucher", "Journal Voucher"], answer: "Contra Voucher"},
    {question: "Which shortcut opens the day book report?", options: ["Alt+D", "Ctrl+D", "F4", "F5"], answer: "F4"},
    {question: "Which key opens the purchase voucher screen?", options: ["F9", "F8", "F7", "F6"], answer: "F9"},
    {question: "Which key opens the sales voucher screen?", options: ["F8", "F9", "F7", "F6"], answer: "F8"},
    {question: "Which key combination is used to cancel a voucher?", options: ["Alt+X", "Ctrl+X", "Shift+X", "Esc"], answer: "Alt+X"},
    {question: "Which key combination is used to recall a voucher?", options: ["Alt+R", "Ctrl+R", "Shift+R", "F4"], answer: "Alt+R"},
    {question: "Which key is used to display ledger summary?", options: ["Alt+L", "Ctrl+L", "F2", "F3"], answer: "Alt+L"},
    {question: "Which option is used to reconcile bank in Tally ERP 9?", options: ["Reconcile", "Bank Reconciliation", "Bank Ledger", "Cash/Bank Book"], answer: "Reconcile"},
    {question: "Which key is used to open the GST report?", options: ["Alt+G", "Ctrl+G", "F11", "F12"], answer: "Alt+G"},
    {question: "Which key is used to open the stock journal voucher?", options: ["F7", "F6", "F5", "F4"], answer: "F7"},
    {question: "Which key is used to alter stock item in a voucher?", options: ["Alt+A", "Ctrl+A", "Alt+S", "Ctrl+S"], answer: "Alt+A"},
    {question: "Which key combination is used to create stock item on the fly?", options: ["Alt+C", "Ctrl+S", "Alt+S", "Ctrl+C"], answer: "Alt+C"},
    {question: "Which key opens the ledger report for reconciliation?", options: ["Alt+R", "Ctrl+R", "F12", "F11"], answer: "Alt+R"},
    {question: "Which key combination is used to tally audit data?", options: ["F3", "F11", "F12", "Alt+A"], answer: "F3"},
    {question: "Which key is used to toggle calculator in voucher entry?", options: ["Alt+C", "Ctrl+C", "F6", "F7"], answer: "Alt+C"},
    {question: "Which key combination is used to print reports in multiple copies?", options: ["Alt+P", "Ctrl+P", "F10", "F12"], answer: "Alt+P"},
    {question: "Which key opens the purchase order voucher?", options: ["F9", "F10", "F11", "F12"], answer: "F10"},
    {question: "Which key opens the sales order voucher?", options: ["F8", "F9", "F10", "F11"], answer: "F8"},
    {question: "Which key is used to view stock item movement?", options: ["Alt+M", "Ctrl+M", "F5", "F6"], answer: "Alt+M"},
    {question: "Which key is used to view stock summary report?", options: ["Alt+S", "Ctrl+S", "F3", "F4"], answer: "Alt+S"},
    {question: "Which key combination is used to create a new cost center?", options: ["Alt+C", "Ctrl+C", "Alt+X", "Ctrl+X"], answer: "Alt+C"},
    {question: "Which key combination is used to create a new cost category?", options: ["Alt+C", "Ctrl+C", "Alt+X", "Ctrl+X"], answer: "Alt+C"},
    {question: "Which key is used to view ledger outstanding report?", options: ["Alt+O", "Ctrl+O", "F4", "F5"], answer: "Alt+O"},
    {question: "Which key is used to create a new voucher type?", options: ["Alt+C", "Ctrl+V", "Alt+V", "Ctrl+N"], answer: "Alt+C"},
    {question: "Which key opens the ledger reconciliation screen?", options: ["Alt+R", "Ctrl+R", "F12", "F11"], answer: "Alt+R"},
    {question: "Which key is used to create a new bank ledger?", options: ["Alt+C", "Ctrl+C", "Alt+B", "Ctrl+B"], answer: "Alt+C"},
    {question: "Which key is used to create a new group while entering ledger?", options: ["Alt+C", "Ctrl+G", "Alt+G", "Ctrl+C"], answer: "Alt+C"},
 {question: "Which key combination is used to print a voucher?", options: ["Alt+P", "Ctrl+P", "F12", "F11"], answer: "Alt+P"},
  {question: "Which key is used to view day book in Tally ERP 9?", options: ["Alt+D", "F2", "F4", "F7"], answer: "Alt+D"},
  {question: "Which report provides details of purchases return?", options: ["Purchase Register", "Sales Register", "Stock Summary", "Ledger"], answer: "Purchase Register"},
  {question: "Which key opens the 'Payment Advice' screen?", options: ["Alt+P", "F4", "Ctrl+P", "F5"], answer: "F5"},
  {question: "Which function key is used to print reports?", options: ["Alt+P", "Ctrl+P", "F12", "F11"], answer: "Alt+P"},
  {question: "Which key is used to view voucher class details?", options: ["Alt+V", "Ctrl+V", "F11", "F12"], answer: "F12"},
  {question: "Which report shows party-wise ledger balance?", options: ["Outstanding Receivables", "Ledger", "Day Book", "Trial Balance"], answer: "Outstanding Receivables"},
  {question: "Which key is used to backup a company?", options: ["Alt+F3", "Ctrl+F3", "Alt+B", "F12"], answer: "Alt+B"},
  {question: "Which key is used to restore company data?", options: ["Alt+R", "Ctrl+R", "F12", "F11"], answer: "Alt+R"},
  {question: "Which key combination is used to alter stock item while in voucher entry?", options: ["Alt+A", "Ctrl+A", "F3", "F4"], answer: "Alt+A"},
  {question: "Which key is used to enable Cost Centre Allocation?", options: ["F11: Features", "F12: Configuration", "Alt+C", "Ctrl+C"], answer: "F11: Features"},
  {question: "Which report shows day-wise bank transactions?", options: ["Cash/Bank Book", "Ledger", "Trial Balance", "Stock Summary"], answer: "Cash/Bank Book"},
  {question: "Which key opens the 'Inventory Books' menu?", options: ["Alt+I", "Ctrl+I", "F11", "F12"], answer: "Alt+I"},
  {question: "Which key combination is used to switch between companies?", options: ["Alt+F1", "Alt+F2", "Alt+F3", "Ctrl+F3"], answer: "Alt+F3"},
  {question: "Which key is used to record contra entries?", options: ["F4", "F5", "F6", "F7"], answer: "F4"},
  {question: "Which key is used to alter a voucher after creation?", options: ["Alt+A", "Ctrl+A", "F3", "F4"], answer: "Alt+A"},
  {question: "Which option shows a list of all stock items with opening and closing balances?", options: ["Stock Summary", "Stock Register", "Inventory Books", "Ledger"], answer: "Stock Summary"},
  {question: "Which key opens 'Cheque Printing' screen?", options: ["Alt+C", "Ctrl+C", "F12", "F11"], answer: "Alt+C"},
  {question: "Which key is used to generate VAT reports?", options: ["F11: Features", "F12: Configuration", "Alt+T", "Ctrl+T"], answer: "F11: Features"},
  {question: "Which key allows you to view voucher numbering?", options: ["F12", "F11", "Alt+V", "Ctrl+V"], answer: "F12"},
  {question: "Which key opens the 'Job Costing' menu?", options: ["Alt+J", "Ctrl+J", "F11", "F12"], answer: "Alt+J"},
  {question: "Which report shows the details of payroll for employees?", options: ["Payroll Reports", "Ledger", "Day Book", "Balance Sheet"], answer: "Payroll Reports"},
  {question: "Which key combination allows deleting a company?", options: ["Alt+D", "Ctrl+D", "F3", "F4"], answer: "Alt+D"},
  {question: "Which key opens 'Ledger Outstanding'?", options: ["Alt+O", "Ctrl+O", "F12", "F11"], answer: "Alt+O"},
  {question: "Which key is used to alter stock categories?", options: ["Alt+A", "Ctrl+A", "F11", "F12"], answer: "Alt+A"},
  {question: "Which option is used for multiple GST rates in the same voucher?", options: ["Voucher Class", "Ledger Class", "Stock Item", "Cost Centre"], answer: "Voucher Class"},
  {question: "Which report shows detailed purchases & sales with GST?", options: ["GST Reports", "Ledger", "Trial Balance", "Day Book"], answer: "GST Reports"},
  {question: "Which shortcut opens 'Day Book' report?", options: ["Alt+D", "Ctrl+D", "F4", "F5"], answer: "Alt+D"},
  {question: "Which key is used to accept all entries while exiting a voucher?", options: ["Enter", "Alt+A", "Ctrl+A", "Shift+Enter"], answer: "Enter"},
  {question: "Which report shows stock ageing analysis?", options: ["Stock Summary", "Stock Ageing Report", "Stock Register", "Inventory Books"], answer: "Stock Ageing Report"},
  {question: "Which key opens 'Interest Calculation' screen for ledgers?", options: ["F11", "F12", "Alt+I", "Ctrl+I"], answer: "F11"},
  {question: "Which option enables multi-currency in Tally ERP 9?", options: ["F11: Features", "F12: Configuration", "Alt+M", "Ctrl+M"], answer: "F11: Features"},
  {question: "Which key is used to view 'Payment Advice'?", options: ["F5", "F6", "F7", "F8"], answer: "F5"},
  {question: "Which key combination opens 'Voucher Type Alteration'?", options: ["Alt+A", "Ctrl+A", "F3", "F4"], answer: "Alt+A"},
  {question: "Which report shows detailed journal entries for a period?", options: ["Journal Register", "Day Book", "Ledger", "Trial Balance"], answer: "Journal Register"},
  {question: "Which key opens 'Cost Centre Alteration'?", options: ["Alt+A", "Ctrl+A", "F11", "F12"], answer: "Alt+A"},
  {question: "Which key is used to view payroll configuration?", options: ["F11", "F12", "Alt+P", "Ctrl+P"], answer: "F11"},
  {question: "Which option allows you to create a new godown while entering stock?", options: ["Alt+C", "Ctrl+C", "F11", "F12"], answer: "Alt+C"},
  {question: "Which key combination opens 'Ledger Voucher'?", options: ["Alt+V", "Ctrl+V", "F3", "F4"], answer: "Alt+V"},
  {question: "Which key is used to generate balance sheet with multiple companies?", options: ["Alt+F1", "Alt+F2", "Alt+F3", "F3"], answer: "Alt+F2"},
  {question: "Which key is used to print a report with predefined settings?", options: ["Alt+P", "Ctrl+P", "F12", "F11"], answer: "Alt+P"},
  {question: "Which key opens 'Day Book Voucher'?", options: ["F2", "F3", "F4", "F5"], answer: "F2"},
  {question: "Which report shows trial balance of multiple companies?", options: ["Trial Balance", "Ledger", "Day Book", "Balance Sheet"], answer: "Trial Balance"},
  {question: "Which key opens 'GST Input Credit' report?", options: ["Alt+G", "Ctrl+G", "F11", "F12"], answer: "Alt+G"},
  {question: "Which key is used to alter company features after creation?", options: ["F11", "F12", "Alt+A", "Ctrl+A"], answer: "F11"},
  {question: "Which option allows multi-location stock tracking?", options: ["Godowns", "Stock Categories", "Stock Groups", "Cost Centres"], answer: "Godowns"},
  {question: "Which key is used to view outstanding purchases?", options: ["Alt+O", "Ctrl+O", "F12", "F11"], answer: "Alt+O"},
  {question: "Which key combination opens 'Bank Reconciliation'?", options: ["Alt+R", "Ctrl+R", "F11", "F12"], answer: "Alt+R"},
  {question: "Which key opens 'Sales Register'?", options: ["Alt+S", "Ctrl+S", "F12", "F11"], answer: "Alt+S"},
  {question: "Which key combination allows multi-account voucher entry?", options: ["Alt+M", "Ctrl+M", "F11", "F12"], answer: "Alt+M"},
  {question: "Which report provides budget variance analysis?", options: ["Budget Report", "Ledger", "Trial Balance", "Balance Sheet"], answer: "Budget Report"},
  {question: "Which voucher type is used to record a bank deposit?", options: ["Receipt Voucher", "Payment Voucher", "Contra Voucher", "Journal Voucher"], answer: "Contra Voucher"},
  {question: "Which voucher records the opening balances of ledger accounts?", options: ["Journal Voucher", "Contra Voucher", "Receipt Voucher", "Payment Voucher"], answer: "Journal Voucher"},
  {question: "Which Tally feature allows automatic calculation of interest on receivables?", options: ["Interest Calculation", "Voucher Class", "Cost Centre", "Budgeting"], answer: "Interest Calculation"},
  {question: "Which report shows all the purchase invoices for a period?", options: ["Purchase Register", "Sales Register", "Stock Summary", "Ledger"], answer: "Purchase Register"},
  {question: "Which voucher type is used to record stock adjustments?", options: ["Stock Journal", "Purchase Voucher", "Sales Voucher", "Journal Voucher"], answer: "Stock Journal"},
  {question: "Which key combination allows you to view day book with multiple voucher types?", options: ["Alt+F1", "Alt+D", "Alt+V", "Ctrl+V"], answer: "Alt+D"},
  {question: "Which feature is used to allocate expenses to multiple cost centers?", options: ["Cost Centre Allocation", "Ledger Groups", "Voucher Classes", "Stock Categories"], answer: "Cost Centre Allocation"},
  {question: "Which report shows detailed VAT or GST payable and receivable?", options: ["GST Reports", "Ledger", "Trial Balance", "Balance Sheet"], answer: "GST Reports"},
  {question: "Which key opens the ledger creation screen directly from voucher entry?", options: ["Alt+C", "Ctrl+C", "F11", "F12"], answer: "Alt+C"},
  {question: "Which report shows stock item-wise sales and purchases?", options: ["Stock Summary", "Stock Register", "Day Book", "Ledger"], answer: "Stock Register"},
  {question: "Which voucher type is used to transfer funds between cash and bank?", options: ["Contra Voucher", "Payment Voucher", "Receipt Voucher", "Journal Voucher"], answer: "Contra Voucher"},
  {question: "Which feature allows you to track multi-location stock?", options: ["Godown", "Stock Group", "Cost Centre", "Voucher Class"], answer: "Godown"},
  {question: "Which report provides age-wise analysis of receivables?", options: ["Outstanding Receivables", "Ledger", "Day Book", "Trial Balance"], answer: "Outstanding Receivables"},
  {question: "Which option allows you to create multiple price levels for stock items?", options: ["Multiple Price Levels", "Stock Categories", "Stock Groups", "Voucher Classes"], answer: "Multiple Price Levels"},
  {question: "Which voucher type is used for recording debit note against purchases?", options: ["Debit Note Voucher", "Sales Voucher", "Journal Voucher", "Payment Voucher"], answer: "Debit Note Voucher"},
  {question: "Which key combination allows printing invoices directly from voucher entry?", options: ["Alt+P", "Ctrl+P", "F12", "F11"], answer: "Alt+P"},
  {question: "Which feature is used to configure GST rates for multiple items?", options: ["Inventory Item GST", "Ledger GST", "Voucher GST", "Cost Centre GST"], answer: "Inventory Item GST"},
  {question: "Which report provides daily cash and bank transaction details?", options: ["Cash/Bank Book", "Ledger", "Day Book", "Trial Balance"], answer: "Cash/Bank Book"},
  {question: "Which voucher type is used for recording payment to suppliers?", options: ["Payment Voucher", "Receipt Voucher", "Sales Voucher", "Contra Voucher"], answer: "Payment Voucher"},
  {question: "Which option allows tracking of budgets against cost centers?", options: ["Budgeting", "Voucher Class", "Ledger Group", "Stock Category"], answer: "Budgeting"},
  {question: "Which report shows profit and loss for a specific period?", options: ["Profit & Loss Account", "Balance Sheet", "Ledger", "Day Book"], answer: "Profit & Loss Account"},
  {question: "Which voucher type is used to record advance payments to suppliers?", options: ["Payment Voucher", "Receipt Voucher", "Journal Voucher", "Sales Voucher"], answer: "Payment Voucher"},
  {question: "Which key combination opens the payroll report for employees?", options: ["Alt+P", "F11", "F12", "Alt+R"], answer: "Alt+P"},
  {question: "Which feature allows creation of multiple stock groups under a parent group?", options: ["Stock Groups", "Stock Categories", "Godowns", "Cost Centres"], answer: "Stock Groups"},
  {question: "Which voucher type is used to record contra entries between two bank accounts?", options: ["Contra Voucher", "Journal Voucher", "Payment Voucher", "Receipt Voucher"], answer: "Contra Voucher"},
  {question: "Which option enables auto calculation of taxes in vouchers?", options: ["Tally Taxation", "Voucher Class", "Ledger Configuration", "Cost Centre Allocation"], answer: "Voucher Class"},
  {question: "Which report shows item-wise profit for a period?", options: ["Stock Summary", "Profit & Loss Account", "Ledger", "Inventory Books"], answer: "Stock Summary"},
  {question: "Which key opens the 'Company Configuration' screen?", options: ["F11: Features", "F12: Configuration", "Alt+F3", "Ctrl+F3"], answer: "F11: Features"},
  {question: "Which voucher type is used to record journal entries not involving cash or bank?", options: ["Journal Voucher", "Payment Voucher", "Receipt Voucher", "Contra Voucher"], answer: "Journal Voucher"},
  {question: "Which feature allows you to reconcile bank statements with ledger entries?", options: ["Bank Reconciliation", "Cash/Bank Book", "Day Book", "Ledger"], answer: "Bank Reconciliation"},
  {question: "Which key combination is used to view detailed ledger report for a party?", options: ["Alt+L", "Ctrl+L", "F11", "F12"], answer: "Alt+L"},
  {question: "Which report provides item-wise stock ageing and expiry details?", options: ["Stock Ageing Report", "Stock Summary", "Stock Register", "Inventory Books"], answer: "Stock Ageing Report"},
  {question: "Which voucher type is used to record debit note against customers?", options: ["Debit Note Voucher", "Sales Voucher", "Journal Voucher", "Receipt Voucher"], answer: "Debit Note Voucher"},
  {question: "Which feature allows tracking of employee attendance and payroll integration?", options: ["Payroll & Attendance", "Cost Centre", "Ledger Group", "Voucher Class"], answer: "Payroll & Attendance"},
  {question: "Which option allows auto rounding of invoices in Tally?", options: ["Voucher Configuration", "Stock Item", "Ledger", "Cost Centre"], answer: "Voucher Configuration"},
  {question: "Which report provides GST Input Tax Credit details?", options: ["GST Reports", "Ledger", "Trial Balance", "Inventory Books"], answer: "GST Reports"},
  {question: "Which key is used to enable multi-currency feature in Tally?", options: ["F11: Features", "F12: Configuration", "Alt+M", "Ctrl+M"], answer: "F11: Features"},
  {question: "Which voucher type is used to record sales return?", options: ["Sales Return Voucher", "Sales Voucher", "Purchase Voucher", "Payment Voucher"], answer: "Sales Return Voucher"},
  {question: "Which report provides summary of receivables and payables for all parties?", options: ["Outstanding Reports", "Ledger", "Day Book", "Trial Balance"], answer: "Outstanding Reports"},
  {question: "Which feature allows creation of multiple price lists for different customers?", options: ["Price Levels", "Stock Categories", "Stock Groups", "Voucher Classes"], answer: "Price Levels"},
  {question: "Which key combination opens the 'Cost Centre Alteration' screen?", options: ["Alt+A", "Ctrl+A", "F11", "F12"], answer: "Alt+A"},
  {question: "Which report shows detailed GST filing summary?", options: ["GST Reports", "Ledger", "Trial Balance", "Balance Sheet"], answer: "GST Reports"},
  {question: "Which option is used to configure TDS in Tally ERP 9?", options: ["F11: Features", "F12: Configuration", "Ledger TDS", "Voucher TDS"], answer: "F11: Features"},
  {question: "Which voucher type is used to record contra between cash and petty cash?", options: ["Contra Voucher", "Payment Voucher", "Receipt Voucher", "Journal Voucher"], answer: "Contra Voucher"},
  {question: "Which feature allows you to create multiple bank accounts under the same bank?", options: ["Bank Groups", "Cost Centre", "Ledger Group", "Voucher Class"], answer: "Bank Groups"},
  {question: "Which key is used to accept a voucher with all entries completed?", options: ["Enter", "Alt+A", "Ctrl+A", "Shift+Enter"], answer: "Enter"},
  {question: "Which report shows cost centre-wise expenses for a period?", options: ["Cost Centre Report", "Ledger", "Day Book", "Trial Balance"], answer: "Cost Centre Report"},
  {question: "Which voucher type is used to record prepayment to vendors?", options: ["Payment Voucher", "Receipt Voucher", "Journal Voucher", "Contra Voucher"], answer: "Payment Voucher"},
  {question: "Which feature allows tracking and allocation of manufacturing expenses?", options: ["Job Costing", "Cost Centre", "Voucher Class", "Ledger Group"], answer: "Job Costing"},
  {question: "Which report shows stock movement for a specific godown?", options: ["Stock Summary", "Stock Register", "Inventory Books", "Ledger"], answer: "Stock Register"},
  {question: "Which voucher type allows recording of opening stock for a new financial year?", options: ["Stock Journal", "Purchase Voucher", "Sales Voucher", "Journal Voucher"], answer: "Stock Journal"},
  {question: "Which feature allows automatic rounding of invoice amounts?", options: ["Voucher Configuration", "Ledger Configuration", "Stock Item Configuration", "Cost Centre Allocation"], answer: "Voucher Configuration"},
  {question: "Which report shows stock item-wise sales analysis for a selected period?", options: ["Stock Summary", "Stock Register", "Day Book", "Ledger"], answer: "Stock Register"},
  {question: "Which feature allows creating multiple warehouse locations under one godown?", options: ["Godown", "Stock Group", "Stock Category", "Cost Centre"], answer: "Godown"},
  {question: "Which key combination is used to view ledger-wise outstanding report?", options: ["Alt+O", "Alt+L", "Ctrl+O", "Ctrl+L"], answer: "Alt+O"},
  {question: "Which report provides month-wise GST collection details?", options: ["GST Reports", "Ledger", "Day Book", "Trial Balance"], answer: "GST Reports"},
  {question: "Which voucher type is used for recording advance receipts from customers?", options: ["Receipt Voucher", "Payment Voucher", "Contra Voucher", "Journal Voucher"], answer: "Receipt Voucher"},
  {question: "Which report shows the list of all ledgers created in a company?", options: ["Ledger Summary", "Trial Balance", "Day Book", "Balance Sheet"], answer: "Ledger Summary"},
  {question: "Which key combination allows deletion of a stock item directly from voucher entry?", options: ["Alt+D", "Ctrl+D", "F3", "F4"], answer: "Alt+D"},
  {question: "Which report provides the net profit or loss for a specific cost centre?", options: ["Profit & Loss Cost Centre Report", "Balance Sheet", "Ledger", "Trial Balance"], answer: "Profit & Loss Cost Centre Report"},
  {question: "Which voucher type is used to record stock transfer between godowns?", options: ["Stock Journal", "Purchase Voucher", "Sales Voucher", "Contra Voucher"], answer: "Stock Journal"},
  {question: "Which key opens the 'Cost Centre Creation' screen?", options: ["Alt+C", "Ctrl+C", "F11", "F12"], answer: "Alt+C"},
  {question: "Which feature allows creation of recurring journal entries automatically?", options: ["Recurring Voucher", "Voucher Class", "Ledger Configuration", "Cost Centre Allocation"], answer: "Recurring Voucher"},
  {question: "Which report provides a comparison of budgeted and actual expenses?", options: ["Budget Report", "Ledger", "Trial Balance", "Balance Sheet"], answer: "Budget Report"},
  {question: "Which voucher type is used to record sales return to a supplier?", options: ["Purchase Return Voucher", "Sales Return Voucher", "Payment Voucher", "Journal Voucher"], answer: "Purchase Return Voucher"},
  {question: "Which key combination allows you to switch between single and multiple company view?", options: ["Alt+F1", "Alt+F2", "Alt+F3", "Ctrl+F3"], answer: "Alt+F3"},
  {question: "Which feature allows creating multiple payroll categories for employees?", options: ["Payroll Configuration", "Ledger Configuration", "Voucher Class", "Cost Centre Allocation"], answer: "Payroll Configuration"},
  {question: "Which report shows employee-wise salary details for a selected period?", options: ["Payroll Report", "Ledger", "Day Book", "Trial Balance"], answer: "Payroll Report"},
  {question: "Which voucher type is used to record a debit note received from a supplier?", options: ["Debit Note Voucher", "Credit Note Voucher", "Journal Voucher", "Payment Voucher"], answer: "Debit Note Voucher"},
  {question: "Which key combination allows printing of all outstanding invoices for customers?", options: ["Alt+P", "Ctrl+P", "F12", "F11"], answer: "Alt+P"},
  {question: "Which report shows item-wise valuation of closing stock?", options: ["Stock Summary", "Stock Register", "Inventory Books", "Ledger"], answer: "Stock Summary"},
  {question: "Which feature allows automatic allocation of expenses to multiple projects?", options: ["Job Costing", "Cost Centre", "Voucher Class", "Ledger Group"], answer: "Job Costing"},
  {question: "Which key opens 'Bank Reconciliation' screen?", options: ["Alt+R", "Ctrl+R", "F11", "F12"], answer: "Alt+R"},
  {question: "Which voucher type is used to record a contra entry between cash and bank?", options: ["Contra Voucher", "Payment Voucher", "Receipt Voucher", "Journal Voucher"], answer: "Contra Voucher"},
  {question: "Which report provides party-wise outstanding payments for suppliers?", options: ["Outstanding Payables", "Ledger", "Day Book", "Trial Balance"], answer: "Outstanding Payables"},
  {question: "Which feature allows configuration of TDS for vendors?", options: ["F11: Features", "F12: Configuration", "Ledger TDS", "Voucher TDS"], answer: "F11: Features"},
  {question: "Which voucher type is used to record journal entry for adjustment of prepayments?", options: ["Journal Voucher", "Payment Voucher", "Receipt Voucher", "Contra Voucher"], answer: "Journal Voucher"},
  {question: "Which report shows godown-wise stock movement for a period?", options: ["Stock Register", "Stock Summary", "Inventory Books", "Ledger"], answer: "Stock Register"},
  {question: "Which feature allows you to configure GST for multiple stock items at once?", options: ["Inventory GST", "Ledger GST", "Voucher GST", "Cost Centre GST"], answer: "Inventory GST"},
  {question: "Which key combination allows viewing of all ledgers under a group?", options: ["Alt+G", "Ctrl+G", "F11", "F12"], answer: "Alt+G"},
  {question: "Which voucher type is used to record payment against advance received?", options: ["Payment Voucher", "Receipt Voucher", "Contra Voucher", "Journal Voucher"], answer: "Payment Voucher"},
  {question: "Which report shows detailed ageing analysis of receivables by party?", options: ["Outstanding Receivables", "Ledger", "Day Book", "Trial Balance"], answer: "Outstanding Receivables"},
  {question: "Which feature allows tracking of multiple price levels for customers and suppliers?", options: ["Price Levels", "Voucher Class", "Ledger Group", "Cost Centre"], answer: "Price Levels"},
  {question: "Which voucher type is used to record journal entries for depreciation?", options: ["Journal Voucher", "Stock Journal", "Contra Voucher", "Payment Voucher"], answer: "Journal Voucher"},
  {question: "Which report provides supplier-wise purchase analysis?", options: ["Purchase Register", "Stock Summary", "Ledger", "Day Book"], answer: "Purchase Register"},
  {question: "Which feature allows creation of multiple units of measurement for stock items?", options: ["Units of Measure", "Stock Group", "Stock Category", "Voucher Class"], answer: "Units of Measure"},
  {question: "Which key is used to accept a voucher after all entries are complete?", options: ["Enter", "Alt+A", "Ctrl+A", "Shift+Enter"], answer: "Enter"},
  {question: "Which report shows customer-wise outstanding invoices?", options: ["Outstanding Receivables", "Ledger", "Day Book", "Trial Balance"], answer: "Outstanding Receivables"},
  {question: "Which feature allows creation of multiple bank accounts under a single bank group?", options: ["Bank Groups", "Cost Centre", "Ledger Group", "Voucher Class"], answer: "Bank Groups"},
  {question: "Which voucher type is used to record sales against multiple price lists?", options: ["Sales Voucher", "Sales Order", "Sales Invoice", "Sales Return Voucher"], answer: "Sales Voucher"},
  {question: "Which key combination allows switching between single and multiple company views?", options: ["Alt+F1", "Alt+F2", "Alt+F3", "Ctrl+F3"], answer: "Alt+F3"},
  {question: "Which report shows month-wise budget utilization for each cost centre?", options: ["Budget Report", "Ledger", "Trial Balance", "Balance Sheet"], answer: "Budget Report"},
  {question: "Which feature allows allocation of indirect expenses to products or projects?", options: ["Job Costing", "Cost Centre Allocation", "Voucher Class", "Ledger Group"], answer: "Job Costing"},
  {question: "Which report shows item-wise sales and purchases with GST?", options: ["GST Reports", "Stock Register", "Ledger", "Day Book"], answer: "GST Reports"},
  {question: "Which voucher type is used to record contra entry between cash and petty cash?", options: ["Contra Voucher", "Payment Voucher", "Receipt Voucher", "Journal Voucher"], answer: "Contra Voucher"},
  {question: "Which feature allows automated calculation of payroll for employees based on attendance?", options: ["Payroll & Attendance", "Voucher Class", "Cost Centre", "Ledger Group"], answer: "Payroll & Attendance"},
  {question: "Which report shows daily cash collection for a period?", options: ["Cash/Bank Book", "Ledger", "Day Book", "Trial Balance"], answer: "Cash/Bank Book"},
  {question: "Which key opens the 'Employee Creation' screen directly?", options: ["Alt+C", "Ctrl+C", "F11", "F12"], answer: "Alt+C"},
  {question: "Which report shows item-wise stock valuation with opening, received, and closing balances?", options: ["Stock Summary", "Stock Register", "Inventory Books", "Ledger"], answer: "Stock Summary"},
  {question: "Which voucher type is used to record prepayment to employees for expenses?", options: ["Payment Voucher", "Receipt Voucher", "Contra Voucher", "Journal Voucher"], answer: "Payment Voucher"},
  {question: "Which feature allows creation of multiple payroll categories for different departments?", options: ["Payroll Configuration", "Ledger Group", "Voucher Class", "Cost Centre Allocation"], answer: "Payroll Configuration"}
 
],
  web: [
    { question: "HTML stands for?", options: ["Hyper Text Markup Language","Home Tool Markup Language","High Tech Machine Language"], answer: "Hyper Text Markup Language" },
    { question: "Which tag is used for line break?", options: ["< br >","< break >","u","lb"], answer: "< br >" },
    { question: "The <a> tag is used for?", options: ["Hyperlink","Paragraph","Heading","Image"], answer: "Hyperlink" },
  ],
  html: [
    { question: "The <p> tag is used for?", options: ["Paragraph","Picture","Padding","Page"], answer: "Paragraph" },
    { question: "The <h1> tag is used for?", options: ["Heading 1","Paragraph","Bold Text","Italic Text"], answer: "Heading 1" }
  ],
  css: [
    { question: "Which property changes text color?", options: ["color","font-color","text-color"], answer: "color" },
    { question: "Which property changes background color?", options: ["background-color","bgcolor","color"], answer: "background-color" }
  ],
  js: [
    { question: "Which symbol is used for comments?", options: ["//","/* */","#"], answer: "//" },
    { question: "How do you declare a variable in JS?", options: ["var x","let x","const x","All"], answer: "All" }
  ],
  basic:[{question: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Peripheral Unit", "Control Processing Unit"], answer: "Central Processing Unit"},
  {question: "Which device is used to point and click on a computer?", options: ["Keyboard", "Mouse", "Monitor", "Printer"], answer: "Mouse"},
  {question: "Which software is used for typing documents?", options: ["MS Word", "Excel", "PowerPoint", "Notepad"], answer: "MS Word"},
  {question: "Which is the primary memory of a computer?", options: ["ROM", "RAM", "Hard Disk", "CD"], answer: "RAM"},
  {question: "Which device is used to print documents?", options: ["Monitor", "Printer", "Keyboard", "Mouse"], answer: "Printer"},
   {question: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Control Processing Unit", "Central Peripheral Unit"], answer: "Central Processing Unit"},
  {question: "Which device is used to point and click?", options: ["Keyboard", "Mouse", "Monitor", "Printer"], answer: "Mouse"},
  {question: "Which software is used to create text documents?", options: ["MS Word", "Excel", "PowerPoint", "Notepad"], answer: "MS Word"},
  {question: "Which is the primary memory of a computer?", options: ["ROM", "RAM", "Hard Disk", "Cache"], answer: "RAM"},
  {question: "Which device is used to print documents?", options: ["Printer", "Monitor", "Keyboard", "Scanner"], answer: "Printer"},
  {question: "Which part of the computer stores permanent data?", options: ["ROM", "RAM", "Cache", "Registers"], answer: "ROM"},
  {question: "Which key combination is used to copy in Windows?", options: ["Ctrl+C", "Ctrl+V", "Ctrl+X", "Ctrl+Z"], answer: "Ctrl+C"},
  {question: "Which key combination is used to paste in Windows?", options: ["Ctrl+V", "Ctrl+C", "Ctrl+X", "Ctrl+Z"], answer: "Ctrl+V"},
  {question: "Which key combination is used to cut in Windows?", options: ["Ctrl+X", "Ctrl+C", "Ctrl+V", "Ctrl+Z"], answer: "Ctrl+X"},
  {question: "Which key combination is used to undo an action?", options: ["Ctrl+Z", "Ctrl+Y", "Ctrl+X", "Ctrl+V"], answer: "Ctrl+Z"},
  {question: "Which software is used to create spreadsheets?", options: ["Excel", "Word", "PowerPoint", "Notepad"], answer: "Excel"},
  {question: "Which software is used for presentations?", options: ["PowerPoint", "Word", "Excel", "Paint"], answer: "PowerPoint"},
  {question: "Which key combination opens Task Manager in Windows?", options: ["Ctrl+Shift+Esc", "Ctrl+Alt+Del", "Alt+Tab", "Ctrl+Esc"], answer: "Ctrl+Shift+Esc"},
  {question: "Which of the following is an input device?", options: ["Keyboard", "Monitor", "Printer", "Speaker"], answer: "Keyboard"},
  {question: "Which of the following is an output device?", options: ["Printer", "Keyboard", "Mouse", "Scanner"], answer: "Printer"},
  {question: "Which memory is volatile?", options: ["RAM", "ROM", "Hard Disk", "Flash Drive"], answer: "RAM"},
  {question: "Which memory is non-volatile?", options: ["ROM", "RAM", "Cache", "Registers"], answer: "ROM"},
  {question: "Which device is used to read optical discs?", options: ["CD/DVD Drive", "Hard Disk", "SSD", "RAM"], answer: "CD/DVD Drive"},
  {question: "Which is the brain of the computer?", options: ["CPU", "RAM", "Hard Disk", "Motherboard"], answer: "CPU"},
  {question: "Which part of the computer holds the processor?", options: ["Motherboard", "RAM", "Hard Disk", "Monitor"], answer: "Motherboard"},
  {question: "Which device is used to capture images digitally?", options: ["Scanner", "Printer", "Monitor", "Keyboard"], answer: "Scanner"},
  {question: "Which is used to store portable data?", options: ["Pen Drive", "RAM", "ROM", "CPU"], answer: "Pen Drive"},
  {question: "Which device is used to output sound?", options: ["Speaker", "Printer", "Monitor", "Keyboard"], answer: "Speaker"},
  {question: "Which device converts digital signals into audio?", options: ["Speaker", "Monitor", "Printer", "Scanner"], answer: "Speaker"},
  {question: "Which is a type of non-volatile storage?", options: ["Hard Disk", "RAM", "Cache", "Registers"], answer: "Hard Disk"},
  {question: "Which software is used to create and edit images?", options: ["Paint", "Word", "Excel", "PowerPoint"], answer: "Paint"},
  {question: "Which of the following is not an operating system?", options: ["MS Word", "Windows 10", "Linux", "Mac OS"], answer: "MS Word"},
  {question: "Which of the following is an operating system?", options: ["Linux", "MS Word", "Excel", "PowerPoint"], answer: "Linux"},
  {question: "Which key combination is used to select all items?", options: ["Ctrl+A", "Ctrl+C", "Ctrl+X", "Ctrl+V"], answer: "Ctrl+A"},
  {question: "Which key combination is used to redo an action?", options: ["Ctrl+Y", "Ctrl+Z", "Ctrl+X", "Ctrl+C"], answer: "Ctrl+Y"},
  {question: "Which file extension is used by MS Word?", options: [".docx", ".xlsx", ".pptx", ".txt"], answer: ".docx"},
  {question: "Which file extension is used by MS Excel?", options: [".xlsx", ".docx", ".pptx", ".txt"], answer: ".xlsx"},
  {question: "Which file extension is used by MS PowerPoint?", options: [".pptx", ".docx", ".xlsx", ".txt"], answer: ".pptx"},
  {question: "Which is the smallest unit of data in a computer?", options: ["Bit", "Byte", "Nibble", "Word"], answer: "Bit"},
  {question: "Which is equal to 8 bits?", options: ["Byte", "Bit", "Word", "Nibble"], answer: "Byte"},
  {question: "Which device provides network connectivity?", options: ["NIC", "Monitor", "Printer", "Keyboard"], answer: "NIC"},
  {question: "Which is used to browse the internet?", options: ["Browser", "Word", "Excel", "Paint"], answer: "Browser"},
  {question: "Which protocol is used for sending emails?", options: ["SMTP", "HTTP", "FTP", "IP"], answer: "SMTP"},
  {question: "Which protocol is used to access websites?", options: ["HTTP", "SMTP", "FTP", "POP3"], answer: "HTTP"},
  {question: "Which protocol is used for file transfer?", options: ["FTP", "HTTP", "SMTP", "POP3"], answer: "FTP"},
  {question: "Which key is used to refresh a webpage?", options: ["F5", "F1", "F2", "F3"], answer: "F5"},
  {question: "Which device stores BIOS settings?", options: ["CMOS Battery", "RAM", "ROM", "CPU"], answer: "CMOS Battery"},
  {question: "Which device connects multiple computers?", options: ["Switch", "CPU", "RAM", "Monitor"], answer: "Switch"},
  {question: "Which is used to prevent unauthorized access?", options: ["Firewall", "Printer", "Monitor", "Keyboard"], answer: "Firewall"},
  {question: "Which is used to detect viruses?", options: ["Antivirus", "Firewall", "Browser", "Scanner"], answer: "Antivirus"},
  {question: "Which device is required for video conferencing?", options: ["Webcam", "Printer", "Scanner", "Monitor"], answer: "Webcam"},
  {question: "Which is an example of input device?", options: ["Keyboard", "Speaker", "Printer", "Monitor"], answer: "Keyboard"},
  {question: "Which is an example of output device?", options: ["Monitor", "Keyboard", "Mouse", "Scanner"], answer: "Monitor"},
  {question: "Which type of memory is cache?", options: ["Volatile", "Non-volatile", "External", "Offline"], answer: "Volatile"},
  {question: "Which of the following is software?", options: ["MS Word", "Keyboard", "CPU", "Monitor"], answer: "MS Word"},
  {question: "Which software allows spreadsheet calculations?", options: ["MS Excel", "MS Word", "MS PowerPoint", "Paint"], answer: "MS Excel"},
  {question: "Which software is used for presentations?", options: ["MS PowerPoint", "MS Excel", "MS Word", "Notepad"], answer: "MS PowerPoint"},
  {question: "Which is the fastest type of memory?", options: ["Cache", "RAM", "ROM", "Hard Disk"], answer: "Cache"},
  {question: "Which is used to permanently store data?", options: ["Hard Disk", "RAM", "Cache", "Registers"], answer: "Hard Disk"},
  {question: "Which component is used for arithmetic calculations?", options: ["ALU", "CU", "Memory", "Register"], answer: "ALU"},
  {question: "Which component controls the operations of CPU?", options: ["Control Unit", "ALU", "RAM", "ROM"], answer: "Control Unit"},
  {question: "Which is used to display text and graphics?", options: ["Monitor", "Printer", "Keyboard", "Mouse"], answer: "Monitor"},
  {question: "Which is used to connect a computer to the internet?", options: ["Router", "Printer", "Monitor", "Keyboard"], answer: "Router"},
  {question: "Which device converts digital data to analog signals?", options: ["Modem", "Monitor", "Printer", "Keyboard"], answer: "Modem"},
  {question: "Which device connects LAN to WAN?", options: ["Router", "Switch", "Hub", "NIC"], answer: "Router"},
  {question: "Which key combination is used to save a file?", options: ["Ctrl+S", "Ctrl+P", "Ctrl+V", "Ctrl+C"], answer: "Ctrl+S"},
  {question: "Which key combination is used to print a document?", options: ["Ctrl+P", "Ctrl+S", "Ctrl+V", "Ctrl+C"], answer: "Ctrl+P"},
  {question: "Which key combination is used to open a new document in Word?", options: ["Ctrl+N", "Ctrl+O", "Ctrl+S", "Ctrl+P"], answer: "Ctrl+N"},
  {question: "Which key combination is used to open a saved document?", options: ["Ctrl+O", "Ctrl+N", "Ctrl+S", "Ctrl+P"], answer: "Ctrl+O"},
  {question: "Which key combination is used to close a window?", options: ["Alt+F4", "Ctrl+W", "Ctrl+F4", "Shift+F4"], answer: "Alt+F4"},
  {question: "Which is a temporary memory?", options: ["RAM", "ROM", "Hard Disk", "SSD"], answer: "RAM"},
  {question: "Which is permanent storage?", options: ["Hard Disk", "RAM", "Cache", "Registers"], answer: "Hard Disk"},
  {question: "Which network topology connects all computers in a circle?", options: ["Ring", "Bus", "Star", "Mesh"], answer: "Ring"},
  {question: "Which network topology connects all computers to a central hub?", options: ["Star", "Bus", "Ring", "Mesh"], answer: "Star"},
  {question: "Which network topology uses a single backbone cable?", options: ["Bus", "Star", "Ring", "Mesh"], answer: "Bus"},
  {question: "Which topology connects each node to every other node?", options: ["Mesh", "Star", "Bus", "Ring"], answer: "Mesh"},
  {question: "Which is used to prevent data loss during power failure?", options: ["UPS", "CPU", "Monitor", "Keyboard"], answer: "UPS"},
  {question: "Which of these is a search engine?", options: ["Google", "Windows", "MS Word", "Excel"], answer: "Google"},
  {question: "Which is used to protect a computer from malware?", options: ["Antivirus", "Firewall", "Router", "Printer"], answer: "Antivirus"},
  {question: "Which protocol is used for receiving emails?", options: ["POP3", "SMTP", "FTP", "HTTP"], answer: "POP3"},
  {question: "Which protocol is used to send emails?", options: ["SMTP", "POP3", "FTP", "HTTP"], answer: "SMTP"},
  {question: "Which device is used to store large amounts of data externally?", options: ["External Hard Disk", "RAM", "ROM", "Cache"], answer: "External Hard Disk"},
  {question: "Which device is used to scan printed documents?", options: ["Scanner", "Printer", "Monitor", "Keyboard"], answer: "Scanner"},
  {question: "Which software is used for database management?", options: ["MS Access", "MS Word", "MS Excel", "PowerPoint"], answer: "MS Access"},
  {question: "Which key combination closes the active workbook in Excel?", options: ["Ctrl+W", "Ctrl+S", "Ctrl+N", "Ctrl+O"], answer: "Ctrl+W"},
  {question: "Which is the default extension for Excel 2016 files?", options: [".xlsx", ".xls", ".docx", ".pptx"], answer: ".xlsx"},
  {question: "Which key combination is used to switch between open applications?", options: ["Alt+Tab", "Ctrl+Tab", "Alt+F4", "Ctrl+Alt+Del"], answer: "Alt+Tab"},
  {question: "Which is used to compress files?", options: ["WinRAR", "MS Word", "Excel", "PowerPoint"], answer: "WinRAR"},
  {question: "Which device is used to read/write data from optical disks?", options: ["CD/DVD Drive", "RAM", "ROM", "SSD"], answer: "CD/DVD Drive"},
  {question: "Which device connects a computer to a printer wirelessly?", options: ["Wi-Fi Printer", "Ethernet", "USB", "NIC"], answer: "Wi-Fi Printer"},
  {question: "Which software is used for drawing vector graphics?", options: ["CorelDRAW", "MS Paint", "MS Word", "Excel"], answer: "CorelDRAW"},
  {question: "Which software is used for image editing?", options: ["Photoshop", "MS Paint", "MS Word", "Excel"], answer: "Photoshop"},
  {question: "Which is used for video conferencing?", options: ["Zoom", "MS Word", "Excel", "PowerPoint"], answer: "Zoom"},
  {question: "Which storage device is fastest?", options: ["SSD", "HDD", "RAM", "CD"], answer: "SSD"},
  {question: "Which is a logical storage unit of a computer?", options: ["File", "Folder", "Directory", "All of the above"], answer: "File"},
  {question: "Which is used to create charts in Excel?", options: ["Insert -> Chart", "Format -> Chart", "Home -> Chart", "Review -> Chart"], answer: "Insert -> Chart"},
  {question: "Which key combination is used to bold text?", options: ["Ctrl+B", "Ctrl+I", "Ctrl+U", "Ctrl+Shift+B"], answer: "Ctrl+B"},
  {question: "Which key combination is used to italicize text?", options: ["Ctrl+I", "Ctrl+B", "Ctrl+U", "Ctrl+Shift+I"], answer: "Ctrl+I"},
  {question: "Which key combination is used to underline text?", options: ["Ctrl+U", "Ctrl+B", "Ctrl+I", "Ctrl+Shift+U"], answer: "Ctrl+U"},    {question: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Peripheral Unit", "Control Processing Unit"], answer: "Central Processing Unit"},
    {question: "Which device is used to point and click on a computer?", options: ["Keyboard", "Mouse", "Monitor", "Printer"], answer: "Mouse"},
    {question: "Which of the following is an input device?", options: ["Printer", "Keyboard", "Monitor", "Speaker"], answer: "Keyboard"},
    {question: "Which of the following is an output device?", options: ["Mouse", "Keyboard", "Monitor", "Scanner"], answer: "Monitor"},
    {question: "What is the main function of RAM?", options: ["Permanent storage", "Temporary storage for running programs", "Processing data", "Controlling devices"], answer: "Temporary storage for running programs"},
    {question: "Which key is used to delete the character to the left of the cursor?", options: ["Backspace", "Delete", "Enter", "Shift"], answer: "Backspace"},
    {question: "What does 'HTTP' stand for?", options: ["HyperText Transfer Protocol", "HyperText Transmission Protocol", "Hyper Terminal Transfer Protocol", "HighText Transfer Protocol"], answer: "HyperText Transfer Protocol"},
    {question: "Which of these is system software?", options: ["Microsoft Word", "Windows 10", "Google Chrome", "Adobe Photoshop"], answer: "Windows 10"},
    {question: "What is the smallest unit of data in a computer?", options: ["Byte", "Bit", "Nibble", "Kilobyte"], answer: "Bit"},
    {question: "Which of the following is permanent memory?", options: ["RAM", "ROM", "Cache", "Virtual Memory"], answer: "ROM"},
    {question: "Which computer language is considered a low-level language?", options: ["Assembly language", "Python", "C++", "Java"], answer: "Assembly language"},
    {question: "Which port is commonly used for connecting a keyboard?", options: ["USB", "HDMI", "VGA", "Ethernet"], answer: "USB"},
    {question: "Which device converts digital signals to analog signals?", options: ["Modem", "Router", "Switch", "Hub"], answer: "Modem"},
    {question: "Which of the following is NOT an operating system?", options: ["Linux", "Windows", "MacOS", "Microsoft Office"], answer: "Microsoft Office"},
    {question: "What is the default file extension for Microsoft Word?", options: [".docx", ".txt", ".xls", ".ppt"], answer: ".docx"},
    {question: "Which function key is used to open Help in most programs?", options: ["F1", "F2", "F5", "F12"], answer: "F1"},
    {question: "What does URL stand for?", options: ["Uniform Resource Locator", "Universal Resource Link", "Unified Resource Locator", "Universal Reference Link"], answer: "Uniform Resource Locator"},
    {question: "Which of these is NOT an input device?", options: ["Scanner", "Mouse", "Printer", "Keyboard"], answer: "Printer"},
    {question: "Which of these is used to store large amounts of data permanently?", options: ["Hard Disk", "RAM", "Cache", "ROM"], answer: "Hard Disk"},
    {question: "Which of the following is an example of application software?", options: ["MS Excel", "Windows 10", "Linux", "BIOS"], answer: "MS Excel"},
    {question: "What is the shortcut key for copy in Windows?", options: ["Ctrl + C", "Ctrl + V", "Ctrl + X", "Ctrl + Z"], answer: "Ctrl + C"},
    {question: "Which memory is volatile?", options: ["ROM", "RAM", "Flash", "Hard Disk"], answer: "RAM"},
    {question: "What does BIOS stand for?", options: ["Basic Input Output System", "Binary Input Output System", "Basic Internal Operating System", "Binary Internal Output System"], answer: "Basic Input Output System"},
    {question: "Which device connects computers within a network?", options: ["Switch", "Keyboard", "Monitor", "Printer"], answer: "Switch"},
    {question: "Which of these is used to display visual output?", options: ["Monitor", "Keyboard", "Mouse", "Printer"], answer: "Monitor"},
    {question: "What is the full form of LAN?", options: ["Local Area Network", "Large Area Network", "Long Area Network", "Logical Area Network"], answer: "Local Area Network"},
    {question: "Which component executes instructions in a computer?", options: ["CPU", "RAM", "ROM", "GPU"], answer: "CPU"},
    {question: "Which of the following is a programming language?", options: ["Python", "HTML", "CSS", "HTTP"], answer: "Python"},
    {question: "Which of these is an external storage device?", options: ["Flash Drive", "RAM", "ROM", "Cache"], answer: "Flash Drive"},
    {question: "Which of the following is used to connect to the Internet?", options: ["Modem", "CPU", "RAM", "Hard Disk"], answer: "Modem"},
    {question: "What does GUI stand for?", options: ["Graphical User Interface", "General User Input", "Graphical Unified Input", "General Utility Interface"], answer: "Graphical User Interface"},
    {question: "Which key is used to switch between open applications?", options: ["Alt + Tab", "Ctrl + Tab", "Shift + Tab", "Ctrl + Alt"], answer: "Alt + Tab"},
    {question: "Which of these is NOT a type of computer network?", options: ["LAN", "WAN", "CAN", "PAN"], answer: "CAN"},
    {question: "Which device allows multiple devices to connect to a network?", options: ["Router", "Mouse", "Monitor", "Keyboard"], answer: "Router"},
    {question: "Which of these is used to read data from optical disks?", options: ["CD-ROM Drive", "Hard Disk", "Flash Drive", "RAM"], answer: "CD-ROM Drive"},
    {question: "What is the main function of a computer's power supply?", options: ["Convert electrical energy to suitable voltage", "Store data", "Process instructions", "Connect devices"], answer: "Convert electrical energy to suitable voltage"},
    {question: "Which software is used for creating presentations?", options: ["MS PowerPoint", "MS Word", "MS Excel", "MS Paint"], answer: "MS PowerPoint"},
    {question: "Which of the following is used to browse the Internet?", options: ["Web Browser", "Word Processor", "Spreadsheet", "Database"], answer: "Web Browser"},
    {question: "Which of the following is considered volatile memory?", options: ["RAM", "ROM", "Hard Disk", "Flash Drive"], answer: "RAM"},
    {question: "Which of these is an example of a database software?", options: ["MS Access", "MS Excel", "MS Word", "MS Paint"], answer: "MS Access"},
    {question: "Which key is used to save a document quickly?", options: ["Ctrl + S", "Ctrl + C", "Ctrl + P", "Ctrl + V"], answer: "Ctrl + S"},
    {question: "Which of these stores data permanently in a computer?", options: ["Hard Disk", "RAM", "Cache", "Registers"], answer: "Hard Disk"},
    {question: "Which of the following is NOT a web browser?", options: ["Google Chrome", "Mozilla Firefox", "Internet Explorer", "MS Word"], answer: "MS Word"},
      {question: "What does PDF stand for?", options: ["Portable Document Format", "Private Document File", "Public Data File", "Program Data Format"], answer: "Portable Document Format"},
  {question: "Which of the following is used to edit images?", options: ["MS Paint", "MS Word", "MS Excel", "Notepad"], answer: "MS Paint"},
  {question: "Which device helps in creating physical copies of digital documents?", options: ["Printer", "Monitor", "Keyboard", "Mouse"], answer: "Printer"},
  {question: "Which key combination is used to undo an action?", options: ["Ctrl + Z", "Ctrl + Y", "Ctrl + X", "Ctrl + C"], answer: "Ctrl + Z"},
  {question: "What is the full form of URL?", options: ["Uniform Resource Locator", "Uniform Reference Link", "Universal Resource Link", "Uniform Reference Locator"], answer: "Uniform Resource Locator"},
  {question: "Which of the following is NOT a type of memory?", options: ["ROM", "RAM", "CPU", "Cache"], answer: "CPU"},
  {question: "What is the default extension of Excel files?", options: [".xlsx", ".docx", ".pptx", ".txt"], answer: ".xlsx"},
  {question: "Which protocol is used to send email?", options: ["SMTP", "FTP", "HTTP", "IP"], answer: "SMTP"},
  {question: "Which of the following is a search engine?", options: ["Google", "Internet Explorer", "Mozilla Firefox", "Windows"], answer: "Google"},
  {question: "Which type of software helps in system maintenance?", options: ["Utility Software", "Application Software", "Word Processor", "Browser"], answer: "Utility Software"},
  {question: "What is the primary function of a firewall?", options: ["Security", "Data Storage", "Processing", "Input Handling"], answer: "Security"},
  {question: "Which device is used to connect multiple network devices?", options: ["Hub", "Printer", "Keyboard", "Monitor"], answer: "Hub"},
  {question: "Which type of memory is ROM?", options: ["Non-volatile", "Volatile", "Cache", "Virtual"], answer: "Non-volatile"},
  {question: "Which key is used to refresh a web page?", options: ["F5", "F1", "F2", "F12"], answer: "F5"},
  {question: "Which of the following is NOT an input device?", options: ["Monitor", "Scanner", "Keyboard", "Mouse"], answer: "Monitor"},
  {question: "What is the shortcut key to paste?", options: ["Ctrl + V", "Ctrl + C", "Ctrl + X", "Ctrl + Z"], answer: "Ctrl + V"},
  {question: "Which device reads and writes data on a CD?", options: ["CD-ROM Drive", "Hard Disk", "Flash Drive", "RAM"], answer: "CD-ROM Drive"},
  {question: "Which of the following is NOT a programming language?", options: ["HTML", "Python", "Java", "C++"], answer: "HTML"},
  {question: "Which software is used to create charts and graphs?", options: ["MS Excel", "MS Word", "MS PowerPoint", "MS Paint"], answer: "MS Excel"},
  {question: "Which is the most common input device for computers?", options: ["Keyboard", "Mouse", "Scanner", "Joystick"], answer: "Keyboard"},
  {question: "Which of the following is NOT a browser?", options: ["Google Chrome", "Mozilla Firefox", "Safari", "MS Word"], answer: "MS Word"},
  {question: "Which of the following is a volatile memory?", options: ["RAM", "ROM", "Hard Disk", "Flash Drive"], answer: "RAM"},
  {question: "Which key is used to open the start menu in Windows?", options: ["Windows Key", "Alt", "Ctrl", "Shift"], answer: "Windows Key"},
  {question: "Which software is used for creating presentations?", options: ["MS PowerPoint", "MS Word", "MS Excel", "MS Access"], answer: "MS PowerPoint"},
  {question: "What is the function of a modem?", options: ["Connect to Internet", "Store data", "Process instructions", "Print documents"], answer: "Connect to Internet"},
  {question: "Which is the permanent storage in a computer?", options: ["Hard Disk", "RAM", "Cache", "Registers"], answer: "Hard Disk"},
  {question: "Which is an example of utility software?", options: ["Antivirus", "MS Word", "MS Excel", "Adobe Photoshop"], answer: "Antivirus"},
  {question: "What does LAN stand for?", options: ["Local Area Network", "Large Area Network", "Long Area Network", "Logical Area Network"], answer: "Local Area Network"},
  {question: "Which of the following is an example of cloud storage?", options: ["Google Drive", "Hard Disk", "USB Drive", "RAM"], answer: "Google Drive"},
  {question: "Which of these is used to listen to audio?", options: ["Speakers", "Monitor", "Keyboard", "Mouse"], answer: "Speakers"},
  {question: "Which is the main circuit board in a computer?", options: ["Motherboard", "RAM", "ROM", "CPU"], answer: "Motherboard"},
  {question: "Which type of software allows you to write code?", options: ["IDE", "Browser", "Word Processor", "Paint"], answer: "IDE"},
  {question: "Which device translates domain names to IP addresses?", options: ["DNS Server", "Router", "Switch", "Modem"], answer: "DNS Server"},
  {question: "Which key combination is used to select all text?", options: ["Ctrl + A", "Ctrl + C", "Ctrl + X", "Ctrl + V"], answer: "Ctrl + A"},
  {question: "Which of the following is a non-volatile memory?", options: ["ROM", "RAM", "Cache", "Registers"], answer: "ROM"},
  {question: "Which of the following is used to send and receive emails?", options: ["Email Client", "Browser", "Word Processor", "Spreadsheet"], answer: "Email Client"},
  {question: "Which of these is a secondary storage device?", options: ["Hard Disk", "RAM", "Registers", "Cache"], answer: "Hard Disk"},
  {question: "Which is a graphical operating system?", options: ["Windows", "DOS", "Unix", "Linux CLI"], answer: "Windows"},
  {question: "Which of the following is NOT an example of application software?", options: ["MS Word", "Adobe Photoshop", "Windows 10", "MS Excel"], answer: "Windows 10"},
  {question: "Which of these is used to transfer data between two computers?", options: ["USB Cable", "Keyboard", "Monitor", "Printer"], answer: "USB Cable"},
  {question: "Which of the following is an output device?", options: ["Monitor", "Keyboard", "Mouse", "Scanner"], answer: "Monitor"},
  {question: "What is the main function of the ALU?", options: ["Perform arithmetic and logic operations", "Store data", "Control input/output devices", "Manage files"], answer: "Perform arithmetic and logic operations"},
  {question: "Which of these is used for long-term storage?", options: ["Hard Disk", "RAM", "Cache", "Registers"], answer: "Hard Disk"},
  {question: "Which of the following is a text editor?", options: ["Notepad", "MS Word", "MS Excel", "Paint"], answer: "Notepad"},
  {question: "Which part of CPU controls the operations of the computer?", options: ["Control Unit", "ALU", "Registers", "Cache"], answer: "Control Unit"},
  {question: "Which of the following is used to connect a computer to a network?", options: ["Network Interface Card (NIC)", "Printer", "Scanner", "Monitor"], answer: "Network Interface Card (NIC)"},
  {question: "Which of these is an operating system?", options: ["Windows", "MS Word", "Excel", "Chrome"], answer: "Windows"},
  {question: "Which protocol is used to browse the web?", options: ["HTTP", "FTP", "SMTP", "IMAP"], answer: "HTTP"},
  {question: "What does BIOS stand for?", options: ["Basic Input Output System", "Binary Input Output System", "Basic Internal Operating System", "Binary Internal Output System"], answer: "Basic Input Output System"},
  {question: "Which memory is faster?", options: ["Cache", "RAM", "Hard Disk", "ROM"], answer: "Cache"},
  {question: "Which device is used to convert digital signals to analog?", options: ["Modem", "Router", "Switch", "Hub"], answer: "Modem"},
  {question: "Which of the following is an example of application software?", options: ["MS Word", "Windows", "Linux", "BIOS"], answer: "MS Word"},
  {question: "Which is used to create a website?", options: ["HTML", "MS Word", "MS Excel", "MS Access"], answer: "HTML"},
  {question: "Which of the following stores the IP address of websites?", options: ["DNS", "FTP", "SMTP", "HTTP"], answer: "DNS"},
  {question: "Which of these is a cloud-based service?", options: ["Dropbox", "Hard Disk", "USB Drive", "CD-ROM"], answer: "Dropbox"},
  {question: "Which of the following is used to protect against malware?", options: ["Antivirus Software", "Word Processor", "Spreadsheet", "Browser"], answer: "Antivirus Software"},
  {question: "Which shortcut is used to save a document?", options: ["Ctrl + S", "Ctrl + X", "Ctrl + C", "Ctrl + V"], answer: "Ctrl + S"},
  {question: "Which of the following is a web browser?", options: ["Mozilla Firefox", "MS Word", "MS Excel", "MS PowerPoint"], answer: "Mozilla Firefox"},
  {question: "Which type of network covers a small area?", options: ["LAN", "WAN", "MAN", "VPN"], answer: "LAN"},
  {question: "Which is the brain of the computer?", options: ["CPU", "RAM", "ROM", "Motherboard"], answer: "CPU"},
  {question: "Which device is used to display graphical data?", options: ["Monitor", "Keyboard", "Mouse", "Printer"], answer: "Monitor"},
  {question: "Which key combination is used to copy?", options: ["Ctrl + C", "Ctrl + V", "Ctrl + X", "Ctrl + Z"], answer: "Ctrl + C"},
  {question: "Which type of software is MS Excel?", options: ["Application Software", "System Software", "Utility Software", "Firmware"], answer: "Application Software"},
  {question: "Which of the following is temporary storage?", options: ["RAM", "Hard Disk", "SSD", "Flash Drive"], answer: "RAM"},
  {question: "Which is a wireless network technology?", options: ["Wi-Fi", "Ethernet", "USB", "Bluetooth Cable"], answer: "Wi-Fi"},
  {question: "Which device is used to input handwritten text?", options: ["Graphics Tablet", "Mouse", "Keyboard", "Scanner"], answer: "Graphics Tablet"},
  {question: "Which of these is a popular database software?", options: ["MySQL", "MS Word", "MS Paint", "Chrome"], answer: "MySQL"},
  {question: "Which of the following is a text file format?", options: [".txt", ".jpg", ".mp3", ".mp4"], answer: ".txt"},
  {question: "Which is used to protect sensitive data?", options: ["Encryption", "Compression", "Backup", "Formatting"], answer: "Encryption"},
  {question: "Which device connects a computer to a printer?", options: ["USB Cable", "Ethernet Cable", "HDMI Cable", "VGA Cable"], answer: "USB Cable"},
  {question: "Which of the following is a volatile memory?", options: ["RAM", "ROM", "Flash", "SSD"], answer: "RAM"},
  {question: "Which of these is used to play audio?", options: ["Speakers", "Monitor", "Keyboard", "Mouse"], answer: "Speakers"},
  {question: "Which of the following is a backup device?", options: ["External Hard Drive", "Mouse", "Keyboard", "Monitor"], answer: "External Hard Drive"},
  {question: "Which software allows creating slideshows?", options: ["MS PowerPoint", "MS Word", "MS Excel", "Paint"], answer: "MS PowerPoint"},
  {question: "Which network uses satellites?", options: ["WAN", "LAN", "PAN", "MAN"], answer: "WAN"},
  {question: "Which type of software is an IDE?", options: ["Development Tool", "Utility Software", "Browser", "Application Software"], answer: "Development Tool"},
  {question: "Which of the following is an online storage service?", options: ["Google Drive", "CD-ROM", "Floppy Disk", "USB Drive"], answer: "Google Drive"},
  {question: "Which key is used to switch between open applications?", options: ["Alt + Tab", "Ctrl + Tab", "Ctrl + Alt", "Shift + Tab"], answer: "Alt + Tab"},
  {question: "Which of the following is permanent storage?", options: ["Hard Disk", "RAM", "Cache", "Registers"], answer: "Hard Disk"},
  {question: "Which of these is an example of a file extension?", options: [".docx", "JPEG", "MP3", "All of the above"], answer: "All of the above"},
  {question: "Which type of software manages hardware resources?", options: ["System Software", "Application Software", "Utility Software", "IDE"], answer: "System Software"},
    {question: "Which of the following is an example of firmware?", options: ["BIOS", "MS Word", "Windows OS", "Excel"], answer: "BIOS"},
  {question: "Which of these is used to measure network speed?", options: ["Bandwidth", "Latency", "Ping", "All of the above"], answer: "All of the above"},
  {question: "Which key is used to delete a character before the cursor?", options: ["Backspace", "Delete", "Enter", "Shift"], answer: "Backspace"},
  {question: "Which device is required for video conferencing?", options: ["Webcam", "Printer", "Scanner", "Monitor"], answer: "Webcam"},
  {question: "Which software is used for graphic design?", options: ["Adobe Photoshop", "MS Word", "MS Excel", "Notepad"], answer: "Adobe Photoshop"},
  {question: "Which memory is non-volatile?", options: ["ROM", "RAM", "Cache", "Registers"], answer: "ROM"},
  {question: "Which of these is a programming language?", options: ["Python", "HTML", "CSS", "HTTP"], answer: "Python"},
  {question: "Which of the following is an example of open-source software?", options: ["Linux", "Windows", "MS Office", "Adobe Photoshop"], answer: "Linux"},
  {question: "Which component holds the CPU?", options: ["Motherboard", "Hard Disk", "RAM", "GPU"], answer: "Motherboard"},
  {question: "Which device helps to connect multiple devices on a network?", options: ["Switch", "Router", "Modem", "Hub"], answer: "Switch"},
  {question: "Which key is used to undo an action?", options: ["Ctrl + Z", "Ctrl + Y", "Ctrl + X", "Ctrl + C"], answer: "Ctrl + Z"},
  {question: "Which of the following is an input device?", options: ["Scanner", "Monitor", "Printer", "Speaker"], answer: "Scanner"},
  {question: "Which part of the computer processes instructions?", options: ["CPU", "RAM", "ROM", "Hard Disk"], answer: "CPU"},
  {question: "Which of the following stores data permanently?", options: ["Hard Disk", "RAM", "Cache", "Registers"], answer: "Hard Disk"},
  {question: "Which of the following is used to browse the internet?", options: ["Web Browser", "MS Word", "Excel", "PowerPoint"], answer: "Web Browser"},
  {question: "Which of these is a cloud computing platform?", options: ["AWS", "MS Word", "Excel", "Photoshop"], answer: "AWS"},
  {question: "Which shortcut is used to cut selected content?", options: ["Ctrl + X", "Ctrl + C", "Ctrl + V", "Ctrl + Z"], answer: "Ctrl + X"},
  {question: "Which of the following is a volatile memory?", options: ["RAM", "ROM", "Flash", "SSD"], answer: "RAM"},
  {question: "Which device is used to convert analog signals to digital?", options: ["Modem", "Router", "Switch", "Hub"], answer: "Modem"},
  {question: "Which is an example of presentation software?", options: ["MS PowerPoint", "MS Word", "MS Excel", "Paint"], answer: "MS PowerPoint"},
  {question: "Which type of storage is fastest?", options: ["Cache", "RAM", "Hard Disk", "ROM"], answer: "Cache"},
  {question: "Which of these is a spreadsheet software?", options: ["MS Excel", "MS Word", "MS PowerPoint", "Paint"], answer: "MS Excel"},
  {question: "Which of these is used for virtual meetings?", options: ["Zoom", "MS Word", "Excel", "PowerPoint"], answer: "Zoom"},
  {question: "Which of the following is an example of network topology?", options: ["Star", "Bus", "Ring", "All of the above"], answer: "All of the above"},
  {question: "Which key combination opens Task Manager?", options: ["Ctrl + Shift + Esc", "Ctrl + Alt + Del", "Alt + Tab", "Alt + F4"], answer: "Ctrl + Shift + Esc"},
  {question: "Which of the following is a wireless communication standard?", options: ["Bluetooth", "Ethernet", "USB", "HDMI"], answer: "Bluetooth"},
  {question: "Which of these is an example of database software?", options: ["Oracle", "MS Word", "Excel", "PowerPoint"], answer: "Oracle"},
  {question: "Which protocol is used for email sending?", options: ["SMTP", "HTTP", "FTP", "IMAP"], answer: "SMTP"},
  {question: "Which of the following stores the boot program?", options: ["ROM", "RAM", "Cache", "Registers"], answer: "ROM"},
  {question: "Which of the following is used to manage files?", options: ["File Explorer", "MS Word", "Excel", "PowerPoint"], answer: "File Explorer"},
  {question: "Which network is spread over a large area?", options: ["WAN", "LAN", "PAN", "MAN"], answer: "WAN"},
  {question: "Which of the following is a utility software?", options: ["Antivirus", "MS Word", "MS Excel", "PowerPoint"], answer: "Antivirus"},
  {question: "Which of these is used for creating websites?", options: ["HTML", "Python", "Java", "C++"], answer: "HTML"},
  {question: "Which memory is temporary?", options: ["RAM", "ROM", "Hard Disk", "Flash"], answer: "RAM"},
  {question: "Which key combination is used to paste?", options: ["Ctrl + V", "Ctrl + C", "Ctrl + X", "Ctrl + Z"], answer: "Ctrl + V"},
  {question: "Which of these is a data storage device?", options: ["Hard Disk", "Keyboard", "Mouse", "Monitor"], answer: "Hard Disk"},
  {question: "Which of the following is an example of system software?", options: ["Windows OS", "MS Word", "MS Excel", "Photoshop"], answer: "Windows OS"},
  {question: "Which of these is used to play videos?", options: ["Media Player", "MS Word", "Excel", "PowerPoint"], answer: "Media Player"},
  {question: "Which of these devices is used to scan documents?", options: ["Scanner", "Keyboard", "Mouse", "Monitor"], answer: "Scanner"},
  {question: "Which key is used to enter a new line?", options: ["Enter", "Shift", "Tab", "Ctrl"], answer: "Enter"},
    {question: "Which of the following is used to read optical disks?", options: ["CD-ROM Drive", "Hard Disk", "USB Drive", "Floppy Disk"], answer: "CD-ROM Drive"},
  {question: "Which key combination is used to select all items?", options: ["Ctrl + A", "Ctrl + C", "Ctrl + X", "Ctrl + V"], answer: "Ctrl + A"},
  {question: "Which of the following is not an operating system?", options: ["Linux", "Windows", "MS Word", "macOS"], answer: "MS Word"},
  {question: "Which of these is used to store temporary files?", options: ["Cache", "ROM", "Hard Disk", "Registers"], answer: "Cache"},
  {question: "Which of these devices is used for output?", options: ["Monitor", "Keyboard", "Mouse", "Scanner"], answer: "Monitor"},
  {question: "Which of these is an example of a web browser?", options: ["Google Chrome", "MS Word", "Excel", "PowerPoint"], answer: "Google Chrome"},
  {question: "Which protocol is used for secure web browsing?", options: ["HTTPS", "HTTP", "FTP", "SMTP"], answer: "HTTPS"},
  {question: "Which is used to permanently store data?", options: ["Hard Disk", "RAM", "Cache", "Registers"], answer: "Hard Disk"},
  {question: "Which of the following is a text editor?", options: ["Notepad", "MS Word", "Excel", "PowerPoint"], answer: "Notepad"},
  {question: "Which of the following is a secondary storage device?", options: ["Hard Disk", "RAM", "Cache", "Registers"], answer: "Hard Disk"},
  {question: "Which key combination is used to redo an action?", options: ["Ctrl + Y", "Ctrl + Z", "Ctrl + X", "Ctrl + C"], answer: "Ctrl + Y"},
  {question: "Which of these is used to store BIOS settings?", options: ["CMOS", "RAM", "ROM", "Cache"], answer: "CMOS"},
  {question: "Which of the following is used to display graphics?", options: ["GPU", "CPU", "RAM", "ROM"], answer: "GPU"},
  {question: "Which of these is used for online collaboration?", options: ["Google Docs", "MS Word Offline", "Notepad", "Paint"], answer: "Google Docs"},
  {question: "Which of these is a mobile operating system?", options: ["Android", "Linux", "Windows 10", "MS DOS"], answer: "Android"},
  {question: "Which of the following is a network device?", options: ["Router", "Monitor", "Keyboard", "Printer"], answer: "Router"},
  {question: "Which of these is a spreadsheet function?", options: ["SUM", "COPY", "PASTE", "UNDO"], answer: "SUM"},
  {question: "Which of the following is used to connect computers over long distances?", options: ["WAN", "LAN", "PAN", "MAN"], answer: "WAN"},
  {question: "Which key combination opens a new tab in a browser?", options: ["Ctrl + T", "Ctrl + N", "Ctrl + W", "Ctrl + Shift + T"], answer: "Ctrl + T"},
  {question: "Which of these is used for database management?", options: ["MySQL", "MS Word", "Excel", "PowerPoint"], answer: "MySQL"},
  {question: "Which of these devices is used to input sound?", options: ["Microphone", "Speaker", "Printer", "Monitor"], answer: "Microphone"},
  {question: "Which of the following is a URL?", options: ["https://www.example.com", "192.168.1.1", "10.0.0.1", "All of the above"], answer: "https://www.example.com"},
  {question: "Which type of software helps in virus protection?", options: ["Antivirus", "MS Word", "Excel", "PowerPoint"], answer: "Antivirus"},
  {question: "Which of the following is used to download files?", options: ["FTP", "HTTP", "SMTP", "IMAP"], answer: "FTP"},
  {question: "Which of these is used to manage network resources?", options: ["Network OS", "MS Word", "MS Excel", "Paint"], answer: "Network OS"},
  {question: "Which of the following is a protocol for file transfer?", options: ["FTP", "SMTP", "HTTP", "HTTPS"], answer: "FTP"},
  {question: "Which of these devices is used for reading cards?", options: ["Card Reader", "Monitor", "Keyboard", "Mouse"], answer: "Card Reader"},
  {question: "Which of the following is a presentation tool?", options: ["MS PowerPoint", "MS Word", "Excel", "Paint"], answer: "MS PowerPoint"},
  {question: "Which key combination is used to lock the computer?", options: ["Windows + L", "Ctrl + L", "Alt + L", "Shift + L"], answer: "Windows + L"},
  {question: "Which memory is fastest?", options: ["Cache", "RAM", "Hard Disk", "ROM"], answer: "Cache"},
  {question: "Which of these is an example of a social media platform?", options: ["Facebook", "MS Word", "Excel", "PowerPoint"], answer: "Facebook"},
  {question: "Which of these is used to convert digital to analog?", options: ["Modem", "Router", "Switch", "Hub"], answer: "Modem"},
  {question: "Which of the following is an input/output device?", options: ["Touchscreen", "Keyboard", "Mouse", "Monitor"], answer: "Touchscreen"},
  {question: "Which device is used to increase computer memory?", options: ["RAM Module", "Hard Disk", "CPU", "GPU"], answer: "RAM Module"},
  {question: "Which of these is used to protect data privacy?", options: ["Encryption", "Firewall", "VPN", "All of the above"], answer: "All of the above"},
  {question: "Which key combination is used to open a new window?", options: ["Ctrl + N", "Ctrl + T", "Alt + N", "Shift + N"], answer: "Ctrl + N"},
  {question: "Which of these is a web development language?", options: ["HTML", "Python", "Java", "C++"], answer: "HTML"},
  {question: "Which of the following is used for video editing?", options: ["Adobe Premiere", "MS Word", "Excel", "PowerPoint"], answer: "Adobe Premiere"},
  {question: "Which of these is used for software version control?", options: ["Git", "MS Word", "Excel", "PowerPoint"], answer: "Git"},
  {question: "Which key combination is used to refresh a web page?", options: ["F5", "F2", "F3", "F4"], answer: "F5"},
  {question: "Which of the following is an example of a cloud service?", options: ["Google Drive", "MS Word", "Excel", "PowerPoint"], answer: "Google Drive"},
  {question: "Which device helps connect wireless devices?", options: ["Wi-Fi Router", "Switch", "Hub", "Modem"], answer: "Wi-Fi Router"},
  {question: "Which of the following is a desktop operating system?", options: ["Windows 10", "Android", "iOS", "Ubuntu Mobile"], answer: "Windows 10"},
  {question: "Which is used to identify a website on the internet?", options: ["Domain Name", "IP Address", "Subnet", "Gateway"], answer: "Domain Name"},
  {question: "Which of these is used to create charts?", options: ["MS Excel", "MS Word", "MS PowerPoint", "Paint"], answer: "MS Excel"},
  {question: "Which key is used to enter a command in the command prompt?", options: ["Enter", "Ctrl", "Alt", "Shift"], answer: "Enter"},
  {question: "Which of the following is used to compress files?", options: ["WinRAR", "MS Word", "Excel", "PowerPoint"], answer: "WinRAR"},
  {question: "Which type of network is confined to a building?", options: ["LAN", "WAN", "PAN", "MAN"], answer: "LAN"},
  {question: "Which is an example of graphics software?", options: ["CorelDRAW", "MS Word", "Excel", "PowerPoint"], answer: "CorelDRAW"},
  {question: "Which protocol is used to retrieve emails?", options: ["POP3", "SMTP", "FTP", "HTTP"], answer: "POP3"},
  {question: "Which of these is used for IP address assignment?", options: ["DHCP", "DNS", "SMTP", "HTTP"], answer: "DHCP"},
  {question: "Which of the following is a network topology?", options: ["Star", "Bus", "Ring", "All of the above"], answer: "All of the above"},
  {question: "Which key is used to delete a character after the cursor?", options: ["Delete", "Backspace", "Enter", "Tab"], answer: "Delete"},
  {question: "Which of these is a web server?", options: ["Apache", "MS Word", "Excel", "PowerPoint"], answer: "Apache"},
  {question: "Which of these is used to convert analog signals to digital?", options: ["ADC", "DAC", "CPU", "GPU"], answer: "ADC"},
  {question: "Which of these stores data temporarily?", options: ["RAM", "ROM", "Hard Disk", "Flash Drive"], answer: "RAM"},
  {question: "Which of the following is a protocol for sending emails?", options: ["SMTP", "FTP", "HTTP", "POP3"], answer: "SMTP"},
  {question: "Which key combination is used to undo an action?", options: ["Ctrl + Z", "Ctrl + Y", "Ctrl + X", "Ctrl + C"], answer: "Ctrl + Z"},
  {question: "Which device displays images on the screen?", options: ["Monitor", "Printer", "Keyboard", "Mouse"], answer: "Monitor"},
  {question: "Which of these is a type of malware?", options: ["Virus", "Worm", "Trojan", "All of the above"], answer: "All of the above"},
  {question: "Which of these is a primary storage device?", options: ["RAM", "Hard Disk", "CD", "USB Drive"], answer: "RAM"},
  {question: "Which of these is used to connect multiple computers in a network?", options: ["Switch", "Monitor", "Printer", "Keyboard"], answer: "Switch"},
  {question: "Which of these is used to edit photos?", options: ["Adobe Photoshop", "MS Word", "Excel", "PowerPoint"], answer: "Adobe Photoshop"},
  {question: "Which of the following is a spreadsheet software?", options: ["MS Excel", "MS Word", "PowerPoint", "Paint"], answer: "MS Excel"},
  {question: "Which device is used to project images on a screen?", options: ["Projector", "Monitor", "Printer", "Scanner"], answer: "Projector"},
  {question: "Which is used to protect a computer from power surges?", options: ["UPS", "CPU", "RAM", "Hard Disk"], answer: "UPS"},
  {question: "Which of these is used to organize files?", options: ["File Explorer", "MS Word", "Paint", "Excel"], answer: "File Explorer"},
  {question: "Which key combination closes the current tab in a browser?", options: ["Ctrl + W", "Ctrl + T", "Ctrl + N", "Ctrl + Q"], answer: "Ctrl + W"},
  {question: "Which of these is used to identify network devices?", options: ["IP Address", "MAC Address", "Both", "None"], answer: "Both"},
  {question: "Which is an example of open-source software?", options: ["Linux", "Windows", "macOS", "MS Office"], answer: "Linux"},
  {question: "Which of the following stores permanent data?", options: ["ROM", "RAM", "Cache", "Registers"], answer: "ROM"},
  {question: "Which of these is a computer language?", options: ["Python", "HTML", "Java", "All of the above"], answer: "All of the above"},
  {question: "Which device is used to read data from a magnetic stripe?", options: ["Card Reader", "Scanner", "Monitor", "Printer"], answer: "Card Reader"},
  {question: "Which of these is used for video conferencing?", options: ["Zoom", "MS Word", "Excel", "PowerPoint"], answer: "Zoom"},
  {question: "Which of these is a cloud storage service?", options: ["Google Drive", "MS Word", "Excel", "PowerPoint"], answer: "Google Drive"},
  {question: "Which key combination is used to open Task Manager?", options: ["Ctrl + Shift + Esc", "Ctrl + Alt + Del", "Alt + F4", "Windows + R"], answer: "Ctrl + Shift + Esc"},
  {question: "Which of these is used to backup data?", options: ["External Hard Disk", "RAM", "Cache", "Registers"], answer: "External Hard Disk"},
  {question: "Which device converts digital signals to analog?", options: ["DAC", "ADC", "CPU", "GPU"], answer: "DAC"},
  {question: "Which of these is a storage device?", options: ["USB Drive", "Monitor", "Keyboard", "Mouse"], answer: "USB Drive"},
  {question: "Which of these protocols is used for secure file transfer?", options: ["SFTP", "FTP", "HTTP", "SMTP"], answer: "SFTP"},
  {question: "Which device is used to read QR codes?", options: ["Scanner", "Card Reader", "Camera", "Monitor"], answer: "Camera"},
  {question: "Which is used to create presentations?", options: ["MS PowerPoint", "MS Word", "Excel", "Paint"], answer: "MS PowerPoint"},
  {question: "Which of these is an example of a network?", options: ["LAN", "WAN", "PAN", "All of the above"], answer: "All of the above"},
  {question: "Which key is used to move the cursor to the beginning of a line?", options: ["Home", "End", "Ctrl", "Shift"], answer: "Home"},
  {question: "Which of these is used to compress files?", options: ["WinRAR", "7-Zip", "Both", "MS Word"], answer: "Both"},
  {question: "Which of these devices allows wireless connections?", options: ["Wi-Fi Router", "Switch", "Hub", "Ethernet Cable"], answer: "Wi-Fi Router"},
  {question: "Which of the following is volatile memory?", options: ["RAM", "ROM", "Hard Disk", "Flash Drive"], answer: "RAM"},
  {question: "Which of these is a video editing software?", options: ["Adobe Premiere", "MS Word", "Excel", "PowerPoint"], answer: "Adobe Premiere"},
  {question: "Which key combination is used to print a document?", options: ["Ctrl + P", "Ctrl + S", "Ctrl + C", "Ctrl + X"], answer: "Ctrl + P"},
  {question: "Which of these is used for cybersecurity?", options: ["Firewall", "Antivirus", "VPN", "All of the above"], answer: "All of the above"},
  {question: "Which device stores frequently used instructions?", options: ["Cache", "RAM", "Hard Disk", "ROM"], answer: "Cache"},
  {question: "Which of these is an example of a search engine?", options: ["Google", "Yahoo", "Bing", "All of the above"], answer: "All of the above"},
  {question: "Which of the following is a database software?", options: ["MySQL", "MS Word", "Excel", "PowerPoint"], answer: "MySQL"},
  {question: "Which of these is used to transfer data between computers?", options: ["USB Cable", "HDMI Cable", "VGA Cable", "Ethernet Cable"], answer: "Ethernet Cable"},
  {question: "Which is used to measure data transfer speed?", options: ["Mbps", "Hz", "Volt", "Ampere"], answer: "Mbps"},
  {question: "Which of these is used for programming?", options: ["IDE", "MS Word", "Excel", "PowerPoint"], answer: "IDE"},
  {question: "Which key combination is used to search for text?", options: ["Ctrl + F", "Ctrl + H", "Ctrl + S", "Ctrl + A"], answer: "Ctrl + F"},
  {question: "Which device reads barcodes?", options: ["Barcode Scanner", "Keyboard", "Monitor", "Mouse"], answer: "Barcode Scanner"},
  {question: "Which of these is a network device?", options: ["Router", "Switch", "Hub", "All of the above"], answer: "All of the above"},
  {question: "Which of these is used for web development?", options: ["HTML", "CSS", "JavaScript", "All of the above"], answer: "All of the above"},
  {question: "Which of these is used to input images?", options: ["Scanner", "Monitor", "Printer", "Keyboard"], answer: "Scanner"},
  {question: "Which device controls computer operations?", options: ["CPU", "GPU", "RAM", "ROM"], answer: "CPU"},
  {question: "Which is used for online communication?", options: ["Email", "MS Word", "Excel", "Paint"], answer: "Email"},
  {question: "Which of these is a storage media?", options: ["CD", "DVD", "USB Drive", "All of the above"], answer: "All of the above"},
  {question: "Which device helps display 3D graphics?", options: ["GPU", "CPU", "RAM", "ROM"], answer: "GPU"},
  {question: "Which of the following is used for remote desktop access?", options: ["TeamViewer", "MS Word", "Excel", "Paint"], answer: "TeamViewer"},
  {question: "Which of these is used to host websites?", options: ["Web Server", "MS Word", "Excel", "PowerPoint"], answer: "Web Server"},
  {question: "Which of these is used to protect computer data?", options: ["Backup", "Firewall", "Antivirus", "All of the above"], answer: "All of the above"},
  {question: "Which key combination opens the Run dialog?", options: ["Windows + R", "Ctrl + R", "Alt + R", "Shift + R"], answer: "Windows + R"},
  {question: "Which of these is used to write documents?", options: ["MS Word", "Excel", "PowerPoint", "Paint"], answer: "MS Word"},
  {question: "Which of these is used to calculate formulas?", options: ["MS Excel", "MS Word", "PowerPoint", "Paint"], answer: "MS Excel"},
  {question: "Which of the following is a web protocol?", options: ["HTTP", "SMTP", "FTP", "All of the above"], answer: "All of the above"},
  {question: "Which device allows network connectivity?", options: ["NIC", "Keyboard", "Mouse", "Monitor"], answer: "NIC"},
  {question: "Which of these is used for virtual meetings?", options: ["Zoom", "Skype", "Google Meet", "All of the above"], answer: "All of the above"},
  {question: "Which device converts electrical signals into digital signals?", options: ["Modem", "Switch", "Router", "Hub"], answer: "Modem"}
]
};
